#ifndef SYMBOLS_H
#define SYMBOLS_H
#ifdef __cplusplus
extern "C" {
#endif
extern void _gteMVMVA_cv0_mx0_s12_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv0_mx0_s0_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv0_mx1_s12_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv0_mx1_s0_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv0_mx2_s12_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv0_mx2_s0_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv0_mx3_s12_SYM(psxRegisters *regs);
extern void _gteMVMVA_cv0_mx3_s0_SYM(psxRegisters *regs);
extern void _gteMVMVA_cv1_mx0_s12_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv1_mx0_s0_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv1_mx1_s12_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv1_mx1_s0_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv1_mx2_s12_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv1_mx2_s0_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv1_mx3_s12_SYM(psxRegisters *regs);
extern void _gteMVMVA_cv1_mx3_s0_SYM(psxRegisters *regs);
extern void _gteMVMVA_cv2_mx0_s12_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv2_mx0_s0_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv2_mx1_s12_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv2_mx1_s0_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv2_mx2_s12_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv2_mx2_s0_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv2_mx3_s12_SYM(psxRegisters *regs);
extern void _gteMVMVA_cv2_mx3_s0_SYM(psxRegisters *regs);
extern void _gteMVMVA_cv3_mx0_s12_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv3_mx0_s0_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv3_mx1_s12_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv3_mx1_s0_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv3_mx2_s12_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv3_mx2_s0_SYM(psxRegisters *regs, u32 vxy, s32 vz);
extern void _gteMVMVA_cv3_mx3_s12_SYM(psxRegisters *regs);
extern void _gteMVMVA_cv3_mx3_s0_SYM(psxRegisters *regs);
extern void recRunSYM(unsigned int ptr, unsigned int regs);
extern void _gteOP_s12_SYM(void);
extern void _gteOP_s0_SYM(void);
extern void _gteDPCS_s12_SYM(void);
extern void _gteDPCS_s0_SYM(void);
extern void _gteGPF_s12_SYM(void);
extern void _gteGPF_s0_SYM(void);
extern void _gteSQR_s12_SYM(void);
extern void _gteSQR_s0_SYM(void);
extern void _gteINTPL_s0_SYM(void);
extern void _gteINTPL_s12_SYM(void);
extern void _gteINTPL_block_SYM(void);
extern void _gteDCPL__SYM(void);
extern void _gteRTPS__SYM(void);
extern void _gteNCDS__SYM(void);
extern void _gteNCDT__SYM(void);
extern void _gteCDP__SYM(void);
extern void _gteNCCS__SYM(void);
extern void _gteCC__SYM(void);
extern void _gteNCS__SYM(void);
extern void _gteNCT__SYM(void);
extern void _gteDPCT__SYM(void);
extern void _gteNCCT__SYM(void);
extern void _gteRTPT__SYM(void);
extern void _gteNCLIP_SYM(void);
extern void _gteAVSZ3__SYM(void);
extern void _gteAVSZ4__SYM(void);
extern void _gteGPL_s12_SYM(void);
extern void _gteGPL_s0_SYM(void);

extern void (*_gteMVMVA_cv0_mx0_s12_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv0_mx0_s0_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv0_mx1_s12_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv0_mx1_s0_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv0_mx2_s12_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv0_mx2_s0_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv0_mx3_s12_)(psxRegisters *regs);
extern void (*_gteMVMVA_cv0_mx3_s0_)(psxRegisters *regs);
extern void (*_gteMVMVA_cv1_mx0_s12_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv1_mx0_s0_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv1_mx1_s12_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv1_mx1_s0_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv1_mx2_s12_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv1_mx2_s0_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv1_mx3_s12_)(psxRegisters *regs);
extern void (*_gteMVMVA_cv1_mx3_s0_)(psxRegisters *regs);
extern void (*_gteMVMVA_cv2_mx0_s12_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv2_mx0_s0_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv2_mx1_s12_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv2_mx1_s0_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv2_mx2_s12_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv2_mx2_s0_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv2_mx3_s12_)(psxRegisters *regs);
extern void (*_gteMVMVA_cv2_mx3_s0_)(psxRegisters *regs);
extern void (*_gteMVMVA_cv3_mx0_s12_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv3_mx0_s0_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv3_mx1_s12_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv3_mx1_s0_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv3_mx2_s12_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv3_mx2_s0_)(psxRegisters *regs, u32 vxy, s32 vz);
extern void (*_gteMVMVA_cv3_mx3_s12_)(psxRegisters *regs);
extern void (*_gteMVMVA_cv3_mx3_s0_)(psxRegisters *regs);
extern void (*recRun)(unsigned int ptr, unsigned int regs);
extern void (*_gteOP_s12_)(void);
extern void (*_gteOP_s0_)(void);
extern void (*_gteDPCS_s12_)(void);
extern void (*_gteDPCS_s0_)(void);
extern void (*_gteGPF_s12_)(void);
extern void (*_gteGPF_s0_)(void);
extern void (*_gteSQR_s12_)(void);
extern void (*_gteSQR_s0_)(void);
extern void (*_gteINTPL_s0_)(void);
extern void (*_gteINTPL_s12_)(void);
extern void (*_gteINTPL_block_)(void);
extern void (*_gteDCPL__)(void);
extern void (*_gteRTPS__)(void);
extern void (*_gteNCDS__)(void);
extern void (*_gteNCDT__)(void);
extern void (*_gteCDP__)(void);
extern void (*_gteNCCS__)(void);
extern void (*_gteCC__)(void);
extern void (*_gteNCS__)(void);
extern void (*_gteNCT__)(void);
extern void (*_gteDPCT__)(void);
extern void (*_gteNCCT__)(void);
extern void (*_gteRTPT__)(void);
extern void (*_gteNCLIP_)(void);
extern void (*_gteAVSZ3__)(void);
extern void (*_gteAVSZ4__)(void);
extern void (*_gteGPL_s12_)(void);
extern void (*_gteGPL_s0_)(void);
#ifdef __cplusplus
}
#endif
#endif // SYMBOLS_H
